dist: bionic

language: python
python:
  - "3.7"

addons:
  apt:
    packages:
      - g++
      - freeglut3-dev

install: pip3 install cmake==3.13.1
script:
  - ./scripts/format.sh || travis_terminate 1
  - cmake --version
  - cmake -Bbuild .
  - cmake --build build
